services:
  # Database
  db:
    image: mysql:8.4.5
    container_name: wp-mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    networks:
      - wp_network
    # WordPress
  wordpress:
    depends_on:
      - db
    image: wordpress:6.8-php8.1-fpm
    container_name: wp-wordpress
    volumes:
      - wordpress_data:/var/www/html
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - wp_network

  # Nginx
  nginx:
    image: nginx:1.15.12-alpine
    container_name: wp-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - wp_network

networks:
  wp_network:


volumes:
  db_data:
  wordpress_data:
